### PR TITLE
Update bundle for symfony 3.0

### PR DESCRIPTION
**Pull request by llewellynthomas**
Update bundle to make it symfony 3.0 ready

### CODE REVIEW

**Comment by pkraeutli** [comment]
Cool, thanks! :+1:

**Comment by pkraeutli** [comment]
Just a thought now: don't we need to change the required Symfony version in composer.json now?

**Comment by llewellynthomas** [comment]
@pkraeutli yes will need to add:  "symfony/framework-bundle": "~2.3|~3.0",

**Comment by pkraeutli** [comment]
And please add the 3.0 Symfony version to [.travis.yml](https://github.com/astina/AstinaRedirectManagerBundle/blob/master/.travis.yml)

**Pull request merged**
