### PR TITLE
Some new features

### PR DESCRIPTION
**Pull request by pharman**
Thanks for creating a great bundle. We have incorporated it into our site and needed to make some changes to make it play nice. These are done in a backward-compatible fashion:

- Ability to specify a Doctrine entity manager 
- Ability to override the base Twig layout
- Ability to disable the redirect listener
- Circular redirect prevention (a -> b -> a)

We are still testing this in our QA environment so probably not good to merge _just_ yet. Maybe a feature branch?

### CODE REVIEW

**Comment by pkraeutli** [comment]
Hi there, thanks a lot for the PR! I'll be happy to merge it once it is stable. Travis build seems to fail because xdebug is enabled. I'll disable id.
Just a small thing for now: please get rid of the goto :)

**Comment by pharman** [comment]
No the goto was the best part! ;)

**Comment by pharman** [comment]
Updated the pull request. The SQL query to find redirects seemed to be loading everything in the DB. Suggested a fix. https://github.com/timeoutdigital/AstinaRedirectManagerBundle/commit/198606af0b151fb5ef062d08c1d41321e3ebefb4

**Comment by pharman** [comment]
Yes your right, should be an orX, I'll update it.

**Comment by pharman** [comment]
Have you had any thoughts on using this at scale? Our site handles around 1-2 million page views per day. Our usual strategy is to put some caching layer in front i.e. memcache or redis

**Comment by pkraeutli** [comment]
The whole thing gets quite slow if you have many regex redirects (especially if you are counting the redirects). If you have a "static" site (w/o user login for example) the easiest is to put a Varnish in front of it. Otherwise it should be quite easy to implement a CachingRedirectFinder that wraps the current one.

**Comment by pharman** [comment]
We have a Varnish cache for page caching so that should cover a fair bit of overhead. Unfortunately we have many millions of different pages to serve so a lot will also get through. Varnish seems to allow caching of the actual redirect responses too, investigating that!

**Comment by pharman** [comment]
Hey @pkraeutli. We have put this feature into our production environment. I'll let you know how it goes.

**Comment by pkraeutli** [comment]
Nice! Looking forward to it. :+1:

**Comment by pharman** [comment]
This has been in our production for a week now and seems to be fine. We have only added regular redirects, not regex ones. Some notes:

- Counting redirect "hits" is not very useful when there is a caching layer in front
- The ability to send headers might be nice
- It's still possible to create infinite loops through sneaky deleting of records

**Comment by pkraeutli** [comment]
Thanks a lot for your contribution! Future improvements are always welcome :)

**Comment by pharman** [comment]
Thanks, our sys-admins already have a required feature list... ;)

**Pull request merged**
